# Generated by Django 4.0.5 on 2022-06-15 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contato', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='subject',
            new_name='numero',
        ),
        migrations.AlterField(
            model_name='contact',
            name='nome',
            field=models.CharField(max_length=60),
        ),
    ]
